### ISSUE TITLE
width dan height pada custom bullet list

### ISSUE THREAD

**Issue by ImBobby** [sebastianusbara/edulab-training#4]
list di bawah menggunakan custom bullet
<img width="394" alt="screen shot 2015-12-11 at 9 34 33 am" src="https://cloud.githubusercontent.com/assets/2084193/11734590/5591f6a0-9feb-11e5-96b3-42c103d6cd13.png">

Dari segi teknik sudah benar menggunakan pseudo-element namun kenapa `width` dan `height` diset 100%? Lebih baik diset menjadi ukuran asli dari gambar yang dipakai. Gambar asli dari custom bullet itu adalah 25×23 px, maka set `width: 25px` dan `height: 25px`.

Dengan begitu di page `biaya.html`, class `biaya__button` tidak perlu ada deklarasi property

``` CSS
.biaya__button {
  /* 2 deklarasi ini sudah tidak diperlukan */
  position: relative;
  z-index: 10;
}
```
